
project_id = "wpiwxyifuvjmxagceawt"

[functions.generate-quote]
verify_jwt = true

[functions.generate-bio-summary]
verify_jwt = true

[functions.generate-exercises]
verify_jwt = true

[functions.chat]
verify_jwt = true

